name: Nalu-Wind-Docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{github.ref}}-${{github.head_ref}}-docs
  cancel-in-progress: true

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends doxygen graphviz
          python3 -m pip install --upgrade pip
          pip3 install sphinx sphinx_rtd_theme breathe
      - name: Build
        # execute from top-level nalu-wind directory
        run: |
          echo "::add-matcher::.github/problem-matchers/sphinx.json"
          sphinx-build -M html ./docs/sphinx ./build_docs/manual -W --keep-going -n 2>&1 | tee -a build-output.txt
          # Doxygen output gets parsed wrong by the sphinx problem matcher so unregister it
          echo "::remove-matcher owner=sphinx-problem-matcher-loose-no-severity::"
          echo "::remove-matcher owner=sphinx-problem-matcher-loose::"
          echo "::remove-matcher owner=sphinx-problem-matcher::"
          doxygen ./docs/doxygen/Doxyfile
          mv ./build_docs/manual/html ./documentation
          mv ./build_docs/doxygen/html ./documentation/api_docs
          touch ./documentation/.nojekyll
      - name: Report
        run: |
          echo "::add-matcher::.github/problem-matchers/sphinx.json"
          egrep "WARNING:" build-output.txt | sort | uniq | \
            awk 'BEGIN{i=0}{print $0}{i++}END{print "Warnings: "i}' > build-output-warnings.txt
          cat build-output-warnings.txt
          #exit $(tail -n 1 build-output-warnings.txt | awk '{print $2}')
      - name: Deploy
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: gh-pages
          FOLDER: documentation
          SINGLE_COMMIT: true
